SWIFTC_FLAGS =
LINKER_FLAGS = -Xlinker -L/usr/local/lib

lint:
	swift run swiftlint autocorrect --path Sources/

document:
	swift run jazzy

generate:
	swift run sourcery --sources Sources/CSCB/ --sources Sources/CSCBExternal/ --sources Sources/CSCBTypes/ --templates Templates/ --output Sources/AutoGenerated/

build: generate
	swift build $(SWIFTC_FLAGS) $(LINKER_FLAGS)

test: build
	swift test

release: generate
	lint
	swift build -c release
	document

clean:
	swift build --clean

distclean:
	rm -rf Packages
	swift build --clean

.PHONY: build test distclean init
