SWIFTC_FLAGS =
LINKER_FLAGS = -Xlinker -L/usr/local/lib

lint:
	swiftlint

document:
	jazzy

generate:
	sourcery --sources Sources/chatbot/ --templates Templates/ --output Sources/AutoGenerated/

#build: generate
build:
	swift build $(SWIFTC_FLAGS) $(LINKER_FLAGS)

test: build
	swift test --generate-linuxmain

release: generate
	lint
	swift build -c release
	document

clean:
	swift build --clean

distclean:
	rm -rf Packages
	swift build --clean

.PHONY: build test distclean init
