#if !canImport(ObjectiveC)
import XCTest

extension chatbotTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__chatbotTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(chatbotTests.__allTests__chatbotTests),
    ]
}
#endif
